name: 'Deploy to AWS CloudFormation'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  #   inputs:
  #    region:
  #      description: 'AWS Region to deploy to'
  #       required: true
  #       default: 'ap-south-1'


jobs:
  # This workflow contains a two jobs"
  Cloudformation-check-deploy:
    name: Cloudformation lint validate and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#       - name: cfn-nag-action
#         uses: stelligent/cfn_nag@master
#         with:
#           input_path: cloudformation/template
# #           extra_args: 
# #             ""
      - name: cfn-nag-action
        uses: minchao/cfn-nag-action@v0.1
        with:
          args: "--input-path cloudformation/template"
#       - name: cfn-lint-action
#         uses: ScottBrenner/cfn-lint-action@1.6.1
#         with:
#           args: "cloudformation/**/*.yaml"

      - name: cfn-artifacts
        uses: actions/upload-artifact@v1
        with:
          name: cloudformation-artifacts
          path: cloudformation/

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: ap-south-1

      # Deploy to AWS CloudFormation
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ec2-auto-tag-stack
          template: cloudformation/ec2-auto-tag.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            LambdaRoleName=ec2TaggingRole,
            EventBridgeRuleName=ec2TaggingRule,
            LambdaFunctionName=ec2TaggingFunction
          Capabilities: CAPABILITY_NAMED_IAM
